version: "3.4"
services:
    nf_app:
        build:
            context: .
            dockerfile: docker_app/Dockerfile
        ports:
            - "5002:5002"
        depends_on:
            - db
        restart: unless-stopped
    db:
        build: mssql_database
        environment:
            SA_PASSWORD: "Teste@123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - db_vol:/var/opt/mssql
volumes:
    db_vol: